name: CI
on:
  push:
    branches: [master]

jobs:

  Code-lint:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Download the repository code onto the runner
      - name: Checkout Repository
        uses: actions/checkout@v7

     # Step 2: Install Node.js and configure package caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Speeds up subsequent runs by caching node_modules

      # Step 3: Clean install project dependencies
      - name: Install Dependencies
        run: npm ci

      - name: install linter
        run: npm install eslint --save-dev

      - name: Setup ESLINT config file 
        run: npm init @eslint/config@latest

      # Step 4: Execute the linter script
      - name: Execute Linter
        run: npm run lint
          
  Build-and-push:
    needs: [Code-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        # Step 5: Build the Dockerfile and push the image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard-fe-master:latest
    
